server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/value_eval?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: zhaoliang
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
